### ISSUE TITLE
Difficulties understanding the protocol

### ISSUE THREAD

**Issue by fsteff** [RangerMauve/discovery-swarm-stream#2]
I am currently trying to implement the server side of this in java [discovery-swarm-stream-java](https://github.com/fsteff/discovery-swarm-stream-java) and I have some difficulties to understand the protocol.
- Where does `streamId` come from? My first guess is, that it is a random id generated by the server.
- What is [this function](https://github.com/RangerMauve/discovery-swarm-stream/blob/a2c84e9dc3e4374cc4b8d3e6575769f92c3faa04/index.js#L42) for? Does OPEN and CLOSE mean some sort of state change? (internal state machine?)

**Comment by RangerMauve** [comment]
> Where does streamId come from? 

You're right in that I was thinking it would be a random ID per stream

> Does OPEN and CLOSE mean some sort of state change?

Whenever the server has a new peer's stream ready for the client, it will send an OPEN event to the client with the stream ID so it can start up replication with it or whatever.

CLOSE is emitted from the server to the client when the peer's stream closes, or is emitted from the client when it wants to close the stream.

I was thinking the flow would look like:

- Client opens socket to server
- Client sends "CONNECT" so that the server knows it's legit
- Client sends a JOIN for a discovery key
- Server starts looking for peers
- When the server finds a peer, it opens a connection to it, generates a random ID, puts the id/connection pair in a HashMap (or whatever language equivalent) and sends an OPEN(streamID) event to the client
- The client then constructs a Node stream and emits an event with it for the client-side logic to handle it
- As the server gets data from the peer, it will emit DATA(streamId, data) events to the client
- The client will then send those events to the stream instance it created before
- When the client writes to the stream, it will emit a DATA(streamId, data) event to the server
- If the client or the peer close the stream, it should emit a CLOSE(streamId) event.
